#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Version
VERSION_MAJOR=0
VERSION_MINOR=2

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
android.defaults.buildfeatures.resvalues=false
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=true
android.r8.optimizedResourceShrinking=true
android.builtInKotlin=true
android.newDsl=true

compose.resources.always.generate.accessors=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
