#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M -XX:+UseParallelGC
kotlin.native.jvmArgs=-Xmx4096M

#Gradle
org.gradle.jvmargs=-Xmx4096M -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Version
VERSION_MAJOR=0
VERSION_MINOR=2

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=8
org.gradle.vfs.watch=true
android.defaults.buildfeatures.resvalues=false
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=true
android.r8.optimizedResourceShrinking=true
android.builtInKotlin=true
android.newDsl=true

compose.resources.always.generate.accessors=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

org.gradle.daemon.idletimeout=60000

kotlin.daemon.jvm.options=-XX:MaxMetaspaceSize=384m
kotlin.daemon.keep.alive.time=60