package com.teEcclesia.identity.domain.model

import kotlinx.datetime.LocalDateTime

data class ProfileResponse(
    val id: String,
    val code: String = "",
    val firstName: String,
    val secondName: String,
    val thirdName: String,
    val lastName: String,
    val displayName: String,
    val fullName: String,
    val nationalId: String,
    val phone: String,
    val homePhone: String,
    val email: String,
    val isEmailVerified: Boolean,
    val isPhoneVerified: Boolean,
    val imageUrl: String?,
    val job: String,
    val buildingNo: String,
    val street: String,
    val streetBranch: String,
    val area: String,
    val floor: String,
    val apartment: String,
    val specialMark: String,
    val gender: Gender,
    val status: UserStatus,
    val statusReason: String?,
    val role: com.teEcclesia.shared.domain.model.UserRole,
    val confessionPriest: Priest?,
    val externalConfessionPriestName: String,
    val externalConfessionChurch: String,
    val externalConfessionPhone: String,
    val khademProfile: KhademProfileResponse?,
    val kahenProfile: KahenProfileResponse?,
    val parentProfile: ParentProfileResponse?,
    val ordinationProfile: OrdinationProfileResponse?,
    val makhdoomProfile: MakhdoomProfileResponse?,
    val createdAt: LocalDateTime,
    val actionTakenAt: String? = null
)
